/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class VistaTotal extends javax.swing.JPanel {

    /**
     * Creates new form vistaTotal
     */
    public VistaTotal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        txtValPagContado = new javax.swing.JTextField();
        txtValPag8 = new javax.swing.JTextField();
        txtValPag15 = new javax.swing.JTextField();
        txtValPag30 = new javax.swing.JTextField();
        txtValPag60 = new javax.swing.JTextField();
        txtValPag90 = new javax.swing.JTextField();
        txtTotDesCli = new javax.swing.JTextField();
        txtFin90 = new javax.swing.JTextField();
        txtNeto = new javax.swing.JTextField();
        txtFinContado = new javax.swing.JTextField();
        txtFin8 = new javax.swing.JTextField();
        txtFin15 = new javax.swing.JTextField();
        txtFin30 = new javax.swing.JTextField();
        txtFin60 = new javax.swing.JTextField();
        txtCom90 = new javax.swing.JTextField();
        txtTotPagFin = new javax.swing.JTextField();
        txtComContado = new javax.swing.JTextField();
        txtCom8 = new javax.swing.JTextField();
        txtCom15 = new javax.swing.JTextField();
        txtCom30 = new javax.swing.JTextField();
        txtCom60 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtPor90 = new javax.swing.JTextField();
        txtPorContado = new javax.swing.JTextField();
        txtPor8 = new javax.swing.JTextField();
        txtPor15 = new javax.swing.JTextField();
        txtPor30 = new javax.swing.JTextField();
        txtPor60 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        btnVolver.setText("volver");

        txtValPag60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValPag60ActionPerformed(evt);
            }
        });

        txtFin30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFin30ActionPerformed(evt);
            }
        });

        txtCom90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCom90ActionPerformed(evt);
            }
        });

        jLabel1.setText("#compras contado");

        jLabel2.setText("#compras 8 dias");

        jLabel3.setText("#compras 15 dias");

        jLabel4.setText("#compras 30 dias");

        jLabel5.setText("#compras 60 dias");

        jLabel6.setText("#compras 90 dias");

        jLabel8.setText("financiacion contado");

        jLabel9.setText("financiacion 8 dias");

        jLabel10.setText("financiacion 15 dias");

        jLabel11.setText("financiacion 30 dias");

        jLabel12.setText("financiacion 60 dias");

        jLabel13.setText("financiacion 90 dias");

        jLabel14.setText("neto de compras");

        jLabel15.setText("valPag contado");

        jLabel16.setText("valPag 8 dias");

        jLabel17.setText("valPag 15 dias");

        jLabel18.setText("valpag 30 dias");

        jLabel19.setText("valPag 60 dias");

        jLabel20.setText("valPag 90 dias");

        jLabel21.setText("tot.descontado a los clientes ");

        jLabel22.setText("tot. pagos por financiacion");

        txtPor90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPor90ActionPerformed(evt);
            }
        });

        jLabel23.setText("%");

        jLabel24.setText("%");

        jLabel25.setText("%");

        jLabel26.setText("%");

        jLabel27.setText("%");

        jLabel28.setText("%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtValPag60)
                                    .addComponent(txtValPag30, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValPag15, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValPag8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValPagContado, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValPag90, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFinContado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFin8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFin15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFin30, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFin60, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFin90, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotDesCli, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTotPagFin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtComContado, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCom90, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCom60, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCom30, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCom15, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCom8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtPor90, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPor60, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPor30, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPor15, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPor8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtPorContado, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtValPagContado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel15))
                                                    .addGap(28, 28, 28)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtValPag8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel16))
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtValPag15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel17))
                                            .addGap(18, 18, 18)
                                            .addComponent(txtValPag30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel18))
                                    .addGap(18, 18, 18)
                                    .addComponent(txtValPag60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel19))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtValPag90, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFinContado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFin8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFin15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFin30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFin60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFin90, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtComContado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCom8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtCom15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtCom30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtCom60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtCom90, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPorContado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPor8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPor15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25))
                                .addGap(18, 18, 18)
                                .addComponent(txtPor30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPor60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPor90, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtTotDesCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotPagFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel14)
                    .addComponent(txtNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(btnVolver)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtValPag60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValPag60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValPag60ActionPerformed

    private void txtFin30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFin30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFin30ActionPerformed

    private void txtCom90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCom90ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCom90ActionPerformed

    public JTextField getTxtCom15() {
        return txtCom15;
    }

    public void setTxtCom15(JTextField txtCom15) {
        this.txtCom15 = txtCom15;
    }

    public JTextField getTxtCom30() {
        return txtCom30;
    }

    public void setTxtCom30(JTextField txtCom30) {
        this.txtCom30 = txtCom30;
    }

    public JTextField getTxtCom60() {
        return txtCom60;
    }

    public void setTxtCom60(JTextField txtCom60) {
        this.txtCom60 = txtCom60;
    }

    public JTextField getTxtCom8() {
        return txtCom8;
    }

    public void setTxtCom8(JTextField txtCom8) {
        this.txtCom8 = txtCom8;
    }

    public JTextField getTxtCom90() {
        return txtCom90;
    }

    public void setTxtCom90(JTextField txtCom90) {
        this.txtCom90 = txtCom90;
    }

    public JTextField getTxtComContado() {
        return txtComContado;
    }

    public void setTxtComContado(JTextField txtComContado) {
        this.txtComContado = txtComContado;
    }

    public JTextField getTxtFin15() {
        return txtFin15;
    }

    public void setTxtFin15(JTextField txtFin15) {
        this.txtFin15 = txtFin15;
    }

    public JTextField getTxtFin30() {
        return txtFin30;
    }

    public void setTxtFin30(JTextField txtFin30) {
        this.txtFin30 = txtFin30;
    }

    public JTextField getTxtFin60() {
        return txtFin60;
    }

    public void setTxtFin60(JTextField txtFin60) {
        this.txtFin60 = txtFin60;
    }

    public JTextField getTxtFin8() {
        return txtFin8;
    }

    public void setTxtFin8(JTextField txtFin8) {
        this.txtFin8 = txtFin8;
    }

    public JTextField getTxtFin90() {
        return txtFin90;
    }

    public void setTxtFin90(JTextField txtFin90) {
        this.txtFin90 = txtFin90;
    }

    public JTextField getTxtFinContado() {
        return txtFinContado;
    }

    public void setTxtFinContado(JTextField txtFinContado) {
        this.txtFinContado = txtFinContado;
    }

    public JTextField getTxtNeto() {
        return txtNeto;
    }

    public void setTxtNeto(JTextField txtNeto) {
        this.txtNeto = txtNeto;
    }

    public JTextField getTxtPor15() {
        return txtPor15;
    }

    public void setTxtPor15(JTextField txtPor15) {
        this.txtPor15 = txtPor15;
    }

    public JTextField getTxtPor30() {
        return txtPor30;
    }

    public void setTxtPor30(JTextField txtPor30) {
        this.txtPor30 = txtPor30;
    }

    public JTextField getTxtPor60() {
        return txtPor60;
    }

    public void setTxtPor60(JTextField txtPor60) {
        this.txtPor60 = txtPor60;
    }

    public JTextField getTxtPor8() {
        return txtPor8;
    }

    public void setTxtPor8(JTextField txtPor8) {
        this.txtPor8 = txtPor8;
    }

    public JTextField getTxtPor90() {
        return txtPor90;
    }

    public void setTxtPor90(JTextField txtPor90) {
        this.txtPor90 = txtPor90;
    }

    public JTextField getTxtPorContado() {
        return txtPorContado;
    }

    public void setTxtPorContado(JTextField txtPorContado) {
        this.txtPorContado = txtPorContado;
    }

    public JTextField getTxtTotDesCli() {
        return txtTotDesCli;
    }

    public void setTxtTotDesCli(JTextField txtTotDesCli) {
        this.txtTotDesCli = txtTotDesCli;
    }

    public JTextField getTxtTotPagFin() {
        return txtTotPagFin;
    }

    public void setTxtTotPagFin(JTextField txtTotPagFin) {
        this.txtTotPagFin = txtTotPagFin;
    }

    public JTextField getTxtValPag15() {
        return txtValPag15;
    }

    public void setTxtValPag15(JTextField txtValPag15) {
        this.txtValPag15 = txtValPag15;
    }

    public JTextField getTxtValPag30() {
        return txtValPag30;
    }

    public void setTxtValPag30(JTextField txtValPag30) {
        this.txtValPag30 = txtValPag30;
    }

    public JTextField getTxtValPag60() {
        return txtValPag60;
    }

    public void setTxtValPag60(JTextField txtValPag60) {
        this.txtValPag60 = txtValPag60;
    }

    public JTextField getTxtValPag8() {
        return txtValPag8;
    }

    public void setTxtValPag8(JTextField txtValPag8) {
        this.txtValPag8 = txtValPag8;
    }

    public JTextField getTxtValPag90() {
        return txtValPag90;
    }

    public void setTxtValPag90(JTextField txtValPag90) {
        this.txtValPag90 = txtValPag90;
    }

    public JTextField getTxtValPagContado() {
        return txtValPagContado;
    }

    public void setTxtValPagContado(JTextField txtValPagContado) {
        this.txtValPagContado = txtValPagContado;
    }

    private void txtPor90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPor90ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPor90ActionPerformed

    public JButton getBtnVolver() {
        return btnVolver;
    }

    public void setBtnVolver(JButton btnVolver) {
        this.btnVolver = btnVolver;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCom15;
    private javax.swing.JTextField txtCom30;
    private javax.swing.JTextField txtCom60;
    private javax.swing.JTextField txtCom8;
    private javax.swing.JTextField txtCom90;
    private javax.swing.JTextField txtComContado;
    private javax.swing.JTextField txtFin15;
    private javax.swing.JTextField txtFin30;
    private javax.swing.JTextField txtFin60;
    private javax.swing.JTextField txtFin8;
    private javax.swing.JTextField txtFin90;
    private javax.swing.JTextField txtFinContado;
    private javax.swing.JTextField txtNeto;
    private javax.swing.JTextField txtPor15;
    private javax.swing.JTextField txtPor30;
    private javax.swing.JTextField txtPor60;
    private javax.swing.JTextField txtPor8;
    private javax.swing.JTextField txtPor90;
    private javax.swing.JTextField txtPorContado;
    private javax.swing.JTextField txtTotDesCli;
    private javax.swing.JTextField txtTotPagFin;
    private javax.swing.JTextField txtValPag15;
    private javax.swing.JTextField txtValPag30;
    private javax.swing.JTextField txtValPag60;
    private javax.swing.JTextField txtValPag8;
    private javax.swing.JTextField txtValPag90;
    private javax.swing.JTextField txtValPagContado;
    // End of variables declaration//GEN-END:variables
}
