/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author estra
 */
public class VistaArbol extends javax.swing.JPanel {

    /**
     * Creates new form VistaArbol
     */
    public VistaArbol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblestudiante = new javax.swing.JTable();
        btnPreOrden = new javax.swing.JButton();
        btnInOrden = new javax.swing.JButton();
        btnPostOrden = new javax.swing.JButton();
        btnPorNiveles = new javax.swing.JButton();
        btnContar = new javax.swing.JButton();
        btnAltura = new javax.swing.JButton();
        btnHojas = new javax.swing.JButton();
        btnInternos = new javax.swing.JButton();
        btnBalanceado = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Arbol Binario de estudiantes ");

        tblestudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblestudiante);

        btnPreOrden.setText("Preorden");

        btnInOrden.setText("inOrden");

        btnPostOrden.setText("postOrden");

        btnPorNiveles.setText("porNiveles");

        btnContar.setText("contar");

        btnAltura.setText("Altura");

        btnHojas.setText("hojas");

        btnInternos.setText("Nd. internos");

        btnBalanceado.setText("Balanceado");
        btnBalanceado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceadoActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAltura)
                .addGap(28, 28, 28)
                .addComponent(btnHojas)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPreOrden)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(btnInternos)))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnInOrden)
                                    .addComponent(btnBalanceado))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPostOrden)
                                    .addComponent(btnContar))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(btnPorNiveles))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(btnVolver))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel1)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPreOrden)
                    .addComponent(btnInOrden)
                    .addComponent(btnPostOrden)
                    .addComponent(btnPorNiveles)
                    .addComponent(btnAltura)
                    .addComponent(btnHojas))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInternos)
                    .addComponent(btnBalanceado)
                    .addComponent(btnVolver)
                    .addComponent(btnContar))
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBalanceadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBalanceadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltura;
    private javax.swing.JButton btnBalanceado;
    private javax.swing.JButton btnContar;
    private javax.swing.JButton btnHojas;
    private javax.swing.JButton btnInOrden;
    private javax.swing.JButton btnInternos;
    private javax.swing.JButton btnPorNiveles;
    private javax.swing.JButton btnPostOrden;
    private javax.swing.JButton btnPreOrden;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblestudiante;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAltura() {
        return btnAltura;
    }

    public void setBtnAltura(JButton btnAltura) {
        this.btnAltura = btnAltura;
    }

    public JButton getBtnBalanceado() {
        return btnBalanceado;
    }

    public void setBtnBalanceado(JButton btnBalanceado) {
        this.btnBalanceado = btnBalanceado;
    }

    public JButton getBtnContar() {
        return btnContar;
    }

    public void setBtnContar(JButton btnContar) {
        this.btnContar = btnContar;
    }

    public JButton getBtnHojas() {
        return btnHojas;
    }

    public void setBtnHojas(JButton btnHojas) {
        this.btnHojas = btnHojas;
    }

    public JButton getBtnInOrden() {
        return btnInOrden;
    }

    public void setBtnInOrden(JButton btnInOrden) {
        this.btnInOrden = btnInOrden;
    }

    public JButton getBtnInternos() {
        return btnInternos;
    }

    public void setBtnInternos(JButton btnInternos) {
        this.btnInternos = btnInternos;
    }

    public JButton getBtnPorNiveles() {
        return btnPorNiveles;
    }

    public void setBtnPorNiveles(JButton btnPorNiveles) {
        this.btnPorNiveles = btnPorNiveles;
    }

    public JButton getBtnPostOrden() {
        return btnPostOrden;
    }

    public void setBtnPostOrden(JButton btnPostOrden) {
        this.btnPostOrden = btnPostOrden;
    }

    public JButton getBtnPreOrden() {
        return btnPreOrden;
    }

    public void setBtnPreOrden(JButton btnPreOrden) {
        this.btnPreOrden = btnPreOrden;
    }

    public JButton getBtnVolver() {
        return btnVolver;
    }

    public void setBtnVolver(JButton btnVolver) {
        this.btnVolver = btnVolver;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTblestudiante() {
        return tblestudiante;
    }

    public void setTblestudiante(JTable tblestudiante) {
        this.tblestudiante = tblestudiante;
    }

   

}
